<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<module id="11e7-63b7-05c12bf9-9739-c30e45cd762f">
    <name>树形部门选择框</name>
    <parentId>11e7-6167-730d0ba3-991c-c72710268258</parentId>
    <applicationid>11e7-5f98-d7d66840-917f-e799edecb417</applicationid>
    <description><![CDATA[]]></description>
    <orderNo>8</orderNo>
    <superior>11e7-6167-730d0ba3-991c-c72710268258</superior>
</module>
