<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<module id="11e7-6213-bf65ccf7-991c-c72710268258">
    <name>抄送设置</name>
    <parentId>11e7-6213-9ff677c5-991c-c72710268258</parentId>
    <applicationid>11e7-5f98-d7d66840-917f-e799edecb417</applicationid>
    <description><![CDATA[]]></description>
    <orderNo>4</orderNo>
    <superior>11e7-6213-9ff677c5-991c-c72710268258</superior>
</module>
