<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<module id="11e7-6777-867eb7a8-9f81-63911c9fa2cf">
    <name>甘特视图</name>
    <parentId>11e7-5f99-b48e293e-917f-e799edecb417</parentId>
    <applicationid>11e7-5f98-d7d66840-917f-e799edecb417</applicationid>
    <description><![CDATA[]]></description>
    <orderNo>0</orderNo>
    <superior>11e7-5f99-b48e293e-917f-e799edecb417</superior>
</module>
