<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<module id="11e7-677c-5e0a2bf2-bb6a-ff15ffadffa1">
    <name>表单功能</name>
    <parentId>11e7-6925-dddb6a2a-8a83-bf38d96990bd</parentId>
    <applicationid>11e7-5f98-d7d66840-917f-e799edecb417</applicationid>
    <description><![CDATA[]]></description>
    <orderNo>2</orderNo>
    <superior>11e7-6925-dddb6a2a-8a83-bf38d96990bd</superior>
</module>
