<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<module id="11e7-7e62-7382dbfc-bfd3-4d11407a88d7">
    <name>自由流程</name>
    <parentId>11e7-6213-9ff677c5-991c-c72710268258</parentId>
    <applicationid>11e7-5f98-d7d66840-917f-e799edecb417</applicationid>
    <description><![CDATA[]]></description>
    <orderNo>0</orderNo>
    <superior>11e7-6213-9ff677c5-991c-c72710268258</superior>
</module>
