<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<module id="11e7-6167-730d0ba3-991c-c72710268258">
    <name>表单控件</name>
    <parentId>11e7-6925-dddb6a2a-8a83-bf38d96990bd</parentId>
    <applicationid>11e7-5f98-d7d66840-917f-e799edecb417</applicationid>
    <description><![CDATA[]]></description>
    <orderNo>1</orderNo>
    <superior>11e7-6925-dddb6a2a-8a83-bf38d96990bd</superior>
</module>
