<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<module id="11e7-6634-0272f420-8f1a-bfe936d3ae2a">
    <name>任一审批人通过,则节点通过</name>
    <parentId>11e7-6779-542ba718-bb6a-ff15ffadffa1</parentId>
    <applicationid>11e7-5f98-d7d66840-917f-e799edecb417</applicationid>
    <description><![CDATA[]]></description>
    <orderNo>0</orderNo>
    <superior>11e7-6779-542ba718-bb6a-ff15ffadffa1</superior>
</module>
