<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<module id="11e7-65fc-8c72b108-8f1a-bfe936d3ae2a">
    <name>下拉框</name>
    <parentId>11e7-6167-730d0ba3-991c-c72710268258</parentId>
    <applicationid>11e7-5f98-d7d66840-917f-e799edecb417</applicationid>
    <description><![CDATA[]]></description>
    <orderNo>5</orderNo>
    <superior>11e7-6167-730d0ba3-991c-c72710268258</superior>
</module>
