<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<module id="11e7-66a6-3c8394ea-8f1a-bfe936d3ae2a">
    <name>审批时限设置</name>
    <parentId>11e7-6213-9ff677c5-991c-c72710268258</parentId>
    <applicationid>11e7-5f98-d7d66840-917f-e799edecb417</applicationid>
    <description><![CDATA[]]></description>
    <orderNo>3</orderNo>
    <superior>11e7-6213-9ff677c5-991c-c72710268258</superior>
</module>
