<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<module id="11e7-6167-8e3eb74e-991c-c72710268258">
    <name>列表视图</name>
    <parentId>11e7-5f99-b48e293e-917f-e799edecb417</parentId>
    <applicationid>11e7-5f98-d7d66840-917f-e799edecb417</applicationid>
    <description><![CDATA[]]></description>
    <orderNo>1</orderNo>
    <superior>11e7-5f99-b48e293e-917f-e799edecb417</superior>
</module>
