<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<module id="11e7-660d-dbd64475-9cdb-af6bc8266ed2">
    <name>用户选择框</name>
    <parentId>11e7-6167-730d0ba3-991c-c72710268258</parentId>
    <applicationid>11e7-5f98-d7d66840-917f-e799edecb417</applicationid>
    <description><![CDATA[]]></description>
    <orderNo>9</orderNo>
    <superior>11e7-6167-730d0ba3-991c-c72710268258</superior>
</module>
