<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<module id="11e7-6639-3b014f7b-9cdb-af6bc8266ed2">
    <name>基本信息</name>
    <parentId>11e7-6213-9ff677c5-991c-c72710268258</parentId>
    <applicationid>11e7-5f98-d7d66840-917f-e799edecb417</applicationid>
    <description><![CDATA[]]></description>
    <orderNo>1</orderNo>
    <superior>11e7-6213-9ff677c5-991c-c72710268258</superior>
</module>
