<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<module id="11e7-6705-279cbc6e-bb6a-ff15ffadffa1">
    <name>二维码</name>
    <parentId>11e7-6167-730d0ba3-991c-c72710268258</parentId>
    <applicationid>11e7-5f98-d7d66840-917f-e799edecb417</applicationid>
    <description><![CDATA[]]></description>
    <orderNo>23</orderNo>
    <superior>11e7-6167-730d0ba3-991c-c72710268258</superior>
</module>
