<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<module id="11e7-6796-79142c51-bb6a-ff15ffadffa1">
    <name>交叉报表</name>
    <parentId>11e7-6796-66233cfe-bb6a-ff15ffadffa1</parentId>
    <applicationid>11e7-5f98-d7d66840-917f-e799edecb417</applicationid>
    <description><![CDATA[]]></description>
    <orderNo>1</orderNo>
    <superior>11e7-6796-66233cfe-bb6a-ff15ffadffa1</superior>
</module>
