<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<module id="11e7-62c4-726d30a1-9ee0-b79780204dd6">
    <name>日期选择框</name>
    <parentId>11e7-6167-730d0ba3-991c-c72710268258</parentId>
    <applicationid>11e7-5f98-d7d66840-917f-e799edecb417</applicationid>
    <description><![CDATA[]]></description>
    <orderNo>6</orderNo>
    <superior>11e7-6167-730d0ba3-991c-c72710268258</superior>
</module>
